# example of a configuration file for thermocouple-to-digital converter MAX31855

DAQModule: MAX31855Config
Unit: DEGREES_C # setting unit for temperature (DEGREES_C is the default)
                # possible values:
                #   DEGREES_C
                #   KELVIN
                #   DEGREES_F
