DAQModule: TSL45315Config

# I2CADDR: 0x39 # 0x29 is default, 0x39 alternative
# List of available channels, which can be uncommented, to get the data. The order in the list doesn't matter, as the
# order is constant and is determined by the implementation.
# If nothing is specified, only the illuminance will be selected.
# Channels:
#  - "lux"

# Multiplier, defining measurement time (which is 400ms for 1, 200ms for 2 and 100ms for 4). Adjusting this will also
# result in the change of the channel limits, as they are defined as from 0 to Multiplier * 65535 Lux.
# Multiplier: 1 (default 1, can be also 2 or 4)
