# example config fo VL53L1X distance sensor

DAQModule: VL53LxConfig
type: 1        # sensor type  0: VL53L0X  1: VL53L1X
range : 1      # 1: short   2: long range (this setting only affects the VL531X)
