name: "Create a release"

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of the version (like 1.1.0)'
        required: true

jobs:
  releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract release notes
        uses: ffurrer2/extract-release-notes@v1
        id: extract-release-notes
        with:
          changelog_file: ReleaseNotes.md
      - name: Generate Changelog
        run: echo "${{ steps.extract-release-notes.outputs.release_notes }}" > ReleaseNotes.txt
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.versionName }}
          release_name: PhyPiDAQ v${{ github.event.inputs.versionName }}
          draft: false
          prerelease: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
      - name: Upload license
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./LICENSE
          asset_name: LICENSE
          asset_content_type: text/plain
      - name: Upload release notes
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ReleaseNotes.txt
          asset_name: ReleaseNotes.txt
          asset_content_type: text/plain